version: "1.0"
info:
  model: int-scaffold
packages:
- name: CardIssuanceProject
  gitServerName: VikashgithubRepo
  gitUrl: https://github.com/vikashsharma387/CardIssuanceProject
  gitUsername: vikashsharma387
  gitBranch: main
